name: Test generate_licenses

on: [push]

jobs:
  build:
    strategy:
      os: [ubuntu-latest, macos-latest, windows-latest]
      python-version: [3.6, 3.7, 3.8, 3.9]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --show-source --statistics
    - name: Run unit tests
      run: |
        python tests.py -v
